#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
  global:
    - STEAMWORKS_VERS=SteamWorks-git121
  matrix:
    #- SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9

#And start build!
install:
    # Sourcemod download
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    # SteamWorks download
    - wget http://users.alliedmods.net/~kyles/builds/SteamWorks/$STEAMWORKS_VERS-linux.tar.gz
    - wget http://users.alliedmods.net/~kyles/builds/SteamWorks/$STEAMWORKS_VERS-windows.zip
    - tar -xzf $STEAMWORKS_VERS-linux.tar.gz addons/sourcemod/extensions/SteamWorks.ext.so addons/sourcemod/scripting/include/SteamWorks.inc
    - unzip -j $STEAMWORKS_VERS-windows.zip addons/sourcemod/extensions/SteamWorks.ext.dll -d addons/sourcemod/extensions
before_script:
# TODO Import other modules to compilation
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/bin/smjansson.ext.so" -O addons/sourcemod/extensions/smjansson.ext.so
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/bin/smjansson.ext.dll" -O addons/sourcemod/extensions/smjansson.ext.dll
    - cd addons/sourcemod/scripting/
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc
    - wget "https://raw.githubusercontent.com/Franc1sco/VoiceAnnounceEX/master/scripting/include/voiceannounce_ex.inc" -O include/voiceannounce_ex.inc
    - wget "https://raw.githubusercontent.com/R1KO/VIP-Core/master/addons/sourcemod/scripting/include/vip_core.inc" -O include/vip_core.inc
    - wget "https://raw.githubusercontent.com/Kailo97/smartjaildoors/master/addons/sourcemod/scripting/include/smartjaildoors.inc" -O include/smartjaildoors.inc
    - wget "https://raw.githubusercontent.com/dataviruset/sm-hosties/master/addons/sourcemod/scripting/include/hosties.inc" -O include/hosties.inc
    - wget "https://raw.githubusercontent.com/dataviruset/sm-hosties/master/addons/sourcemod/scripting/include/lastrequest.inc" -O include/lastrequest.inc
    - wget "https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc" -O include/SteamWorks.inc
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/pawn/scripting/include/smjansson.inc" -O include/smjansson.inc
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/pawn/scripting/include/smjansson.inc" -O include/smjansson.inc
# Add multicolors from github repository
    - mkdir include/multicolors
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/colors.inc" -O include/multicolors/colors.inc
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/morecolors.inc" -O include/multicolors/morecolors.inc
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors.inc" -O include/multicolors.inc
# Added Arms-Fix include for CS:GO
    - wget "https://raw.githubusercontent.com/NomisCZ/Arms-Fix/master/addons/sourcemod/scripting/include/n_arms_fix.inc" -O include/n_arms_fix.inc
    - chmod +x spcomp
    - mkdir compiled
script: ./compile.sh jwp_core.sp jwp_admincontrol.sp jwp_bequiet.sp jwp_coloring.sp jwp_dooraimcontrol.sp jwp_doorcontrol.sp jwp_fdnobunt.sp jwp_ff.sp jwp_freeday.sp jwp_guns.sp jwp_handcuffs.sp jwp_healthkit.sp jwp_isolator.sp jwp_laserbeam.sp jwp_mcoloring.sp jwp_mute.sp jwp_noblock.sp jwp_onlrstarted.sp jwp_order.sp jwp_otkaz_m.sp jwp_playsound.sp jwp_pris_counter.sp jwp_rebel.sp jwp_respawn.sp jwp_rextend.sp jwp_skin.sp jwp_slay.sp jwp_speed.sp jwp_stoplr.sp jwp_stripknife.sp jwp_tojail.sp jwp_transwarden.sp jwp_wcolor.sp jwp_whealth.sp jwp_wtimer.sp jwp_icon.sp jwp_shootguns.sp jwp_votewardenkick.sp

#Releases
before_deploy:
    - cd ../../..
    - mkdir jwp jwp/cfg jwp/cfg/jwp jwp/addons jwp/addons/sourcemod jwp/addons/sourcemod/extensions jwp/addons/sourcemod/scripting jwp/addons/sourcemod/scripting/jwp jwp/addons/sourcemod/scripting/include jwp/addons/sourcemod/translations
    - mv addons/sourcemod/extensions/smjansson* jwp/addons/sourcemod/extensions/
    - mv addons/sourcemod/extensions/SteamWorks.ext* jwp/addons/sourcemod/extensions/
    - mv addons/sourcemod/scripting/jwp_*.sp jwp/addons/sourcemod/scripting/
    - mv addons/sourcemod/scripting/jwp/* jwp/addons/sourcemod/scripting/jwp/
    - mv addons/sourcemod/scripting/compiled jwp/addons/sourcemod/plugins
    - mv addons/sourcemod/scripting/include/jwp* jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/morecolors.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/updater.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/voiceannounce_ex.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/vip_core.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/smartjaildoors.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/lastrequest.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/SteamWorks.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/smjansson.inc jwp/addons/sourcemod/scripting/include/
# csgo_colors.inc will be deprecated and removed in the future.
    - mv addons/sourcemod/scripting/include/csgo_colors.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/emitsoundany.inc jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/multicolors* jwp/addons/sourcemod/scripting/include/
    - mv addons/sourcemod/scripting/include/n_arms_fix.inc jwp/addons/sourcemod/scripting/include/
    - rsync -a --prune-empty-dirs --include '*/' --include 'jwp*' --exclude '*' addons/sourcemod/translations/ jwp/addons/sourcemod/translations/
    - mv cfg/jwp/* jwp/cfg/jwp/
    - mv materials jwp/
    - mv sound jwp/
    - mv LICENSE.md jwp/
    - mv README.md jwp/
    - zip -rq jwp jwp
    - tar -czf jwp.tar.gz jwp
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file:
        - jwp.zip
        - jwp.tar.gz
    skip_cleanup: true
    on:
        tags: true

#Notifications
notifications:
    email: false