#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c
#Set the build environment
env:
  global:
    - STEAMWORKS_VERS=SteamWorks-git121
    - INCLUDE=addons/sourcemod/scripting/include
    - SCRIPTING=addons/sourcemod/scripting
    - EXTENSIONS=addons/sourcemod/extensions
  matrix:
    - SMVERSION=1.8
    - SMVERSION=1.9
    
install:
    # Sourcemod download
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    # SteamWorks download
    - wget http://users.alliedmods.net/~kyles/builds/SteamWorks/$STEAMWORKS_VERS-linux.tar.gz
    - wget http://users.alliedmods.net/~kyles/builds/SteamWorks/$STEAMWORKS_VERS-windows.zip
    - tar -xzf $STEAMWORKS_VERS-linux.tar.gz $EXTENSIONS/SteamWorks.ext.so $INCLUDE/SteamWorks.inc
    - unzip -j $STEAMWORKS_VERS-windows.zip $EXTENSIONS/SteamWorks.ext.dll -d $EXTENSIONS
    # Import other modules for successful compilation
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/bin/smjansson.ext.so" -O $EXTENSIONS/smjansson.ext.so
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/bin/smjansson.ext.dll" -O $EXTENSIONS/smjansson.ext.dll
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O $INCLUDE/morecolors.inc
    - wget "https://raw.githubusercontent.com/Franc1sco/VoiceAnnounceEX/master/scripting/include/voiceannounce_ex.inc" -O $INCLUDE/voiceannounce_ex.inc
    - wget "https://raw.githubusercontent.com/R1KO/VIP-Core/master/addons/sourcemod/scripting/include/vip_core.inc" -O $INCLUDE/vip_core.inc
    - wget "https://raw.githubusercontent.com/Kailo97/smartjaildoors/master/addons/sourcemod/scripting/include/smartjaildoors.inc" -O $INCLUDE/smartjaildoors.inc
    - wget "https://raw.githubusercontent.com/dataviruset/sm-hosties/master/addons/sourcemod/scripting/include/hosties.inc" -O $INCLUDE/hosties.inc
    - wget "https://raw.githubusercontent.com/dataviruset/sm-hosties/master/addons/sourcemod/scripting/include/lastrequest.inc" -O $INCLUDE/lastrequest.inc
    - wget "https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc" -O $INCLUDE/SteamWorks.inc
    - wget "https://raw.githubusercontent.com/thraaawn/SMJansson/master/pawn/scripting/include/smjansson.inc" -O $INCLUDE/smjansson.inc
    - wget "https://raw.githubusercontent.com/NomisCZ/Arms-Fix/master/addons/sourcemod/scripting/include/n_arms_fix.inc" -O $INCLUDE/n_arms_fix.inc
    # Add multicolors from github repository
    - mkdir $INCLUDE/multicolors
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/colors.inc" -O $INCLUDE/multicolors/colors.inc
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/morecolors.inc" -O $INCLUDE/multicolors/morecolors.inc
    - wget "https://raw.githubusercontent.com/Bara20/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors.inc" -O $INCLUDE/multicolors.inc
    # Shop support
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop.inc" -O $INCLUDE/shop.inc
    - mkdir $INCLUDE/shop
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/admin.inc" -O $INCLUDE/shop/admin.inc
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/db.inc" -O $INCLUDE/shop/db.inc
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/functions.inc" -O $INCLUDE/shop/functions.inc
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/items.inc" -O $INCLUDE/shop/items.inc
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/players.inc" -O $INCLUDE/shop/players.inc
    - wget "https://raw.githubusercontent.com/R1KO/Shop-Core/dev/addons/sourcemod/scripting/include/shop/register.inc" -O $INCLUDE/shop/register.inc

before_script:
    - chmod +x $SCRIPTING/spcomp
    - mkdir $SCRIPTING/compiled

script:
    - 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash ci/test.sh $TRAVIS_BRANCH; fi'
    - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ci/build.sh $TRAVIS_BRANCH; fi'

#Releases
before_deploy:
    - mkdir jwp jwp/cfg jwp/cfg/jwp jwp/addons jwp/addons/sourcemod jwp/addons/sourcemod/extensions jwp/addons/sourcemod/scripting jwp/addons/sourcemod/scripting/jwp jwp/addons/sourcemod/scripting/include jwp/addons/sourcemod/translations
    - mv $EXTENSIONS/smjansson* jwp/$EXTENSIONS
    - mv $EXTENSIONS/SteamWorks.ext* jwp/$EXTENSIONS
    - mv $SCRIPTING/jwp_*.sp jwp/$SCRIPTING
    - mv $SCRIPTING/jwp/* jwp/$SCRIPTING/jwp/
    - mv $SCRIPTING/compiled jwp/addons/sourcemod/plugins
    - mv $INCLUDE/jwp* jwp/$INCLUDE
    - mv $INCLUDE/morecolors.inc jwp/$INCLUDE
    - mv $INCLUDE/updater.inc jwp/$INCLUDE
    - mv $INCLUDE/voiceannounce_ex.inc jwp/$INCLUDE
    - mv $INCLUDE/vip_core.inc jwp/$INCLUDE
    - mv $INCLUDE/smartjaildoors.inc jwp/$INCLUDE
    - mv $INCLUDE/lastrequest.inc jwp/$INCLUDE
    - mv $INCLUDE/SteamWorks.inc jwp/$INCLUDE
    - mv $INCLUDE/smjansson.inc jwp/$INCLUDE
    # csgo_colors.inc will be deprecated and removed in the future.
    - mv $INCLUDE/csgo_colors.inc jwp/$INCLUDE
    - mv $INCLUDE/emitsoundany.inc jwp/$INCLUDE
    - mv $INCLUDE/multicolors* jwp/$INCLUDE
    - mv $INCLUDE/n_arms_fix.inc jwp/$INCLUDE
    - mv $INCLUDE/shop* jwp/$INCLUDE
    - rsync -a --prune-empty-dirs --include '*/' --include 'jwp*' --exclude '*' addons/sourcemod/translations/ jwp/addons/sourcemod/translations/
    - mv cfg/jwp/* jwp/cfg/jwp/
    - mv materials jwp/
    - mv sound jwp/
    - mv LICENSE.md jwp/
    - mv README.md jwp/
    - zip -rq jwp jwp
    - tar -czf jwp.tar.gz jwp
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file:
        - jwp.zip
        - jwp.tar.gz
    skip_cleanup: true
    on:
        tags: true

#Notifications
notifications:
    email: false